# Generated by Django 3.0 on 2022-12-07 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='crm',
            new_name='cfm',
        ),
    ]
