# Generated by Django 3.0 on 2022-12-07 00:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221206_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nascimento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
