# Generated by Django 3.0 on 2022-12-07 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20221207_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='Doctor',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='Paciente',
            new_name='paciente',
        ),
    ]
