# Generated by Django 3.0 on 2022-12-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20221207_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='doctor',
            new_name='Doctor',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='paciente',
            new_name='Paciente',
        ),
    ]
